# Preprocessing

In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [56]:
df = pd.read_csv("LaptopData.csv")
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [57]:
df.isna().sum()

Unnamed: 0          30
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [58]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1303 rows x 0 columns]

In [22]:
df.fillna(0)

In [63]:
df = df.fillna(method = 'ffill')

C:\Users\71524\AppData\Local\Temp\ipykernel_5636\439241999.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method = 'ffill')

In [25]:
df.fillna(df.mean())

TypeError: can only concatenate str (not "int") to str

In [64]:
df.isna().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [12]:
tem_df = df.copy()

In [15]:
tem_df = tem_df.dropna()

In [19]:
tem_df.isna().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [28]:
df.Inches.unique()

array(['13.3', '15.6', '15.4', '14', '12', nan, '17.3', '13.5', '12.5',
       '13', '18.4', '13.9', '11.6', '25.6', '35.6', '12.3', '27.3', '24',
       '33.5', '?', '31.6', '17', '15', '14.1', '11.3', '10.1'],
      dtype=object)

In [31]:
df[df.Inches.isnull()]

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df.duplicated().sum()

29

In [41]:
df = df.fillna(method = 'ffill')

C:\Users\71524\AppData\Local\Temp\ipykernel_5636\439241999.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method = 'ffill')

In [36]:
df[df.Inches.isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Company, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price]
Index: []

In [42]:
df.isnull().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [38]:
numerical_vars = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_vars = df.select_dtypes(include=['object']).columns.tolist()                           
print('Numerical variables:', numerical_vars)
print('Categorical variables:', categorical_vars)

Numerical variables: ['Unnamed: 0', 'Price']
Categorical variables: ['Company', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight']

In [47]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [72]:
le_company = LabelEncoder()
le_type = LabelEncoder()
le_resolution = LabelEncoder()
le_cpu = LabelEncoder()
le_gpu = LabelEncoder()
le_opsys = LabelEncoder()

In [74]:
df['Company'] = le_company.fit_transform(df['Company'].astype(str))
df['TypeName'] = le_type.fit_transform(df['TypeName'].astype(str))
df['ScreenResolution'] = le_resolution.fit_transform(df['ScreenResolution'].astype(str))
df['Cpu'] = le_cpu.fit_transform(df['Cpu'].astype(str))
df['Gpu'] = le_gpu.fit_transform(df['Gpu'].astype(str))
df['OpSys'] = le_opsys.fit_transform(df['OpSys'].astype(str))

In [53]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,1,4,13.3,16,80,8GB,128GB SSD,64,8,1.37kg,71378.6832
1,1.0,1,4,13.3,1,78,8GB,128GB Flash Storage,57,8,1.34kg,47895.5232
2,2.0,16,3,15.6,38,90,8GB,256GB SSD,59,4,1.86kg,30636.0000
3,3.0,1,4,15.4,18,102,16GB,512GB SSD,99,8,1.83kg,135195.3360
4,4.0,1,4,13.3,16,82,8GB,256GB SSD,65,8,1.37kg,96095.8080

In [54]:
df.tail()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
1298,1298.0,2,0,14,5,106,4GB,128GB SSD,52,5,1.8kg,33992.64
1299,1299.0,2,0,13.3,11,106,16GB,512GB SSD,52,5,1.3kg,79866.72
1300,1300.0,2,3,14,0,46,2GB,64GB Flash Storage,45,5,1.5kg,12201.12
1301,1301.0,16,3,15.6,0,106,6GB,1TB HDD,24,5,2.19kg,40705.92
1302,1302.0,11,3,15.6,0,46,4GB,500GB HDD,45,5,2.2kg,19660.32

In [75]:
print('Company' , le_company.classes_)
print('Type' ,le_type.classes_)
print('Resolution' ,le_resolution.classes_)
print('CPU' ,le_cpu.classes_)
print('GPU' ,le_gpu.classes_)
print('OpSys' ,le_opsys.classes_)

Company ['Acer' 'Apple' 'Asus' 'Chuwi' 'Dell' 'Fujitsu' 'Google' 'HP' 'Huawei'
 'LG' 'Lenovo' 'MSI' 'Mediacom' 'Microsoft' 'Razer' 'Samsung' 'Toshiba'
 'Vero' 'Xiaomi' 'nan']
Type ['2 in 1 Convertible' 'Gaming' 'Netbook' 'Notebook' 'Ultrabook'
 'Workstation' 'nan']
Resolution ['1366x768' '1440x900' '1600x900' '1920x1080' '2560x1440'
 '4K Ultra HD / Touchscreen 3840x2160' '4K Ultra HD 3840x2160'
 'Full HD / Touchscreen 1920x1080' 'Full HD 1920x1080'
 'IPS Panel 1366x768' 'IPS Panel 2560x1440'
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160'
 'IPS Panel 4K Ultra HD 3840x2160'
 'IPS Panel Full HD / Touchscreen 1920x1080' 'IPS Panel Full HD 1366x768'
 'IPS Panel Full HD 1920x1080' 'IPS Panel Full HD 1920x1200'
 'IPS Panel Full HD 2160x1440' 'IPS Panel Full HD 2560x1440'
 'IPS Panel Quad HD+ / Touchscreen 3200x1800'
 'IPS Panel Quad HD+ 2560x1440' 'IPS Panel Quad HD+ 3200x1800'
 'IPS Panel Retina Display 2304x1440' 'IPS Panel Retina Display 2560x1600'
 'IPS Panel Retina Display 2736x1824' 'IPS Panel Retina Display 2880x1800'
 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160'
 'IPS Panel Touchscreen 1366x768' 'IPS Panel Touchscreen 1920x1200'
 'IPS Panel Touchscreen 2400x1600' 'IPS Panel Touchscreen 2560x1440'
 'Quad HD+ / Touchscreen 3200x1800' 'Quad HD+ 3200x1800'
 'Touchscreen / 4K Ultra HD 3840x2160' 'Touchscreen / Full HD 1920x1080'
 'Touchscreen / Quad HD+ 3200x1800' 'Touchscreen 1366x768'
 'Touchscreen 2256x1504' 'Touchscreen 2400x1600' 'Touchscreen 2560x1440'
 'nan']
CPU ['AMD A10-Series 9600P 2.4GHz' 'AMD A10-Series 9620P 2.5GHz'
 'AMD A10-Series A10-9620P 2.5GHz' 'AMD A12-Series 9700P 2.5GHz'
 'AMD A12-Series 9720P 2.7GHz' 'AMD A12-Series 9720P 3.6GHz'
 'AMD A4-Series 7210 2.2GHz' 'AMD A6-Series 7310 2GHz'
 'AMD A6-Series 9220 2.5GHz' 'AMD A6-Series 9220 2.9GHz'
 'AMD A6-Series A6-9220 2.5GHz' 'AMD A8-Series 7410 2.2GHz'
 'AMD A9-Series 9410 2.9GHz' 'AMD A9-Series 9420 2.9GHz'
 'AMD A9-Series 9420 3GHz' 'AMD A9-Series A9-9420 3GHz'
 'AMD E-Series 6110 1.5GHz' 'AMD E-Series 7110 1.8GHz'
 'AMD E-Series 9000 2.2GHz' 'AMD E-Series 9000e 1.5GHz'
 'AMD E-Series E2-6110 1.5GHz' 'AMD E-Series E2-9000 2.2GHz'
 'AMD E-Series E2-9000e 1.5GHz' 'AMD FX 8800P 2.1GHz' 'AMD FX 9830P 3GHz'
 'AMD Ryzen 1600 3.2GHz' 'AMD Ryzen 1700 3GHz'
 'Intel Atom X5-Z8350 1.44GHz' 'Intel Atom Z8350 1.92GHz'
 'Intel Atom x5-Z8300 1.44GHz' 'Intel Atom x5-Z8350 1.44GHz'
 'Intel Atom x5-Z8550 1.44GHz' 'Intel Celeron Dual Core 3205U 1.5GHz'
 'Intel Celeron Dual Core 3855U 1.6GHz'
 'Intel Celeron Dual Core N3050 1.6GHz'
 'Intel Celeron Dual Core N3060 1.60GHz'
 'Intel Celeron Dual Core N3060 1.6GHz'
 'Intel Celeron Dual Core N3350 1.1GHz'
 'Intel Celeron Dual Core N3350 2.0GHz'
 'Intel Celeron Dual Core N3350 2GHz'
 'Intel Celeron Quad Core N3160 1.6GHz'
 'Intel Celeron Quad Core N3450 1.1GHz'
 'Intel Celeron Quad Core N3710 1.6GHz' 'Intel Core M 1.1GHz'
 'Intel Core M 1.2GHz' 'Intel Core M 6Y30 0.9GHz'
 'Intel Core M 6Y54 1.1GHz' 'Intel Core M 6Y75 1.2GHz'
 'Intel Core M 7Y30 1.0GHz' 'Intel Core M M3-6Y30 0.9GHz'
 'Intel Core M M7-6Y75 1.2GHz' 'Intel Core M m3 1.2GHz'
 'Intel Core M m3-7Y30 2.2GHz' 'Intel Core M m7-6Y75 1.2GHz'
 'Intel Core i3 6006U 2.0GHz' 'Intel Core i3 6006U 2.2GHz'
 'Intel Core i3 6006U 2GHz' 'Intel Core i3 6100U 2.1GHz'
 'Intel Core i3 6100U 2.3GHz' 'Intel Core i3 7100U 2.4GHz'
 'Intel Core i3 7130U 2.7GHz' 'Intel Core i5 1.3GHz'
 'Intel Core i5 1.6GHz' 'Intel Core i5 1.8GHz' 'Intel Core i5 2.0GHz'
 'Intel Core i5 2.3GHz' 'Intel Core i5 2.9GHz' 'Intel Core i5 3.1GHz'
 'Intel Core i5 6200U 2.3GHz' 'Intel Core i5 6260U 1.8GHz'
 'Intel Core i5 6300HQ 2.3GHz' 'Intel Core i5 6300U 2.4GHz'
 'Intel Core i5 6440HQ 2.6GHz' 'Intel Core i5 7200U 2.50GHz'
 'Intel Core i5 7200U 2.5GHz' 'Intel Core i5 7200U 2.70GHz'
 'Intel Core i5 7200U 2.7GHz' 'Intel Core i5 7300HQ 2.5GHz'
 'Intel Core i5 7300U 2.6GHz' 'Intel Core i5 7440HQ 2.8GHz'
 'Intel Core i5 7500U 2.7GHz' 'Intel Core i5 7Y54 1.2GHz'
 'Intel Core i5 7Y57 1.2GHz' 'Intel Core i5 8250U 1.6GHz'
 'Intel Core i7 2.2GHz' 'Intel Core i7 2.7GHz' 'Intel Core i7 2.8GHz'
 'Intel Core i7 2.9GHz' 'Intel Core i7 6500U 2.50GHz'
 'Intel Core i7 6500U 2.5GHz' 'Intel Core i7 6560U 2.2GHz'
 'Intel Core i7 6600U 2.6GHz' 'Intel Core i7 6700HQ 2.6GHz'
 'Intel Core i7 6820HK 2.7GHz' 'Intel Core i7 6820HQ 2.7GHz'
 'Intel Core i7 6920HQ 2.9GHz' 'Intel Core i7 7500U 2.5GHz'
 'Intel Core i7 7500U 2.7GHz' 'Intel Core i7 7560U 2.4GHz'
 'Intel Core i7 7600U 2.8GHz' 'Intel Core i7 7660U 2.5GHz'
 'Intel Core i7 7700HQ 2.7GHz' 'Intel Core i7 7700HQ 2.8GHz'
 'Intel Core i7 7820HK 2.9GHz' 'Intel Core i7 7820HQ 2.9GHz'
 'Intel Core i7 7Y75 1.3GHz' 'Intel Core i7 8550U 1.8GHz'
 'Intel Core i7 8650U 1.9GHz' 'Intel Pentium Dual Core 4405U 2.1GHz'
 'Intel Pentium Dual Core 4405Y 1.5GHz'
 'Intel Pentium Dual Core N4200 1.1GHz'
 'Intel Pentium Quad Core N3700 1.6GHz'
 'Intel Pentium Quad Core N3710 1.6GHz'
 'Intel Pentium Quad Core N4200 1.1GHz' 'Intel Xeon E3-1505M V6 3GHz'
 'Intel Xeon E3-1535M v5 2.9GHz' 'Intel Xeon E3-1535M v6 3.1GHz'
 'Samsung Cortex A72&A53 2.0GHz' 'nan']
GPU ['AMD FirePro W4190M' 'AMD FirePro W4190M ' 'AMD FirePro W5130M'
 'AMD FirePro W6150M' 'AMD R17M-M1-70' 'AMD R4 Graphics' 'AMD Radeon 520'
 'AMD Radeon 530' 'AMD Radeon 540' 'AMD Radeon Pro 455'
 'AMD Radeon Pro 555' 'AMD Radeon Pro 560' 'AMD Radeon R2'
 'AMD Radeon R2 Graphics' 'AMD Radeon R3' 'AMD Radeon R4'
 'AMD Radeon R4 Graphics' 'AMD Radeon R5' 'AMD Radeon R5 430'
 'AMD Radeon R5 520' 'AMD Radeon R5 M315' 'AMD Radeon R5 M330'
 'AMD Radeon R5 M420' 'AMD Radeon R5 M420X' 'AMD Radeon R5 M430'
 'AMD Radeon R7' 'AMD Radeon R7 Graphics' 'AMD Radeon R7 M360'
 'AMD Radeon R7 M365X' 'AMD Radeon R7 M440' 'AMD Radeon R7 M445'
 'AMD Radeon R7 M460' 'AMD Radeon R7 M465' 'AMD Radeon R9 M385'
 'AMD Radeon RX 540' 'AMD Radeon RX 550' 'AMD Radeon RX 560'
 'AMD Radeon RX 580' 'ARM Mali T860 MP4' 'Intel Graphics 620'
 'Intel HD Graphics' 'Intel HD Graphics 400' 'Intel HD Graphics 405'
 'Intel HD Graphics 500' 'Intel HD Graphics 505' 'Intel HD Graphics 510'
 'Intel HD Graphics 515' 'Intel HD Graphics 520' 'Intel HD Graphics 530'
 'Intel HD Graphics 5300' 'Intel HD Graphics 540' 'Intel HD Graphics 6000'
 'Intel HD Graphics 615' 'Intel HD Graphics 620' 'Intel HD Graphics 620 '
 'Intel HD Graphics 630' 'Intel Iris Graphics 540'
 'Intel Iris Graphics 550' 'Intel Iris Plus Graphics 640'
 'Intel Iris Plus Graphics 650' 'Intel Iris Pro Graphics'
 'Intel UHD Graphics 620' 'Nvidia GTX 980 SLI' 'Nvidia GeForce 150MX'
 'Nvidia GeForce 920' 'Nvidia GeForce 920M' 'Nvidia GeForce 920MX'
 'Nvidia GeForce 920MX ' 'Nvidia GeForce 930M' 'Nvidia GeForce 930MX'
 'Nvidia GeForce 930MX ' 'Nvidia GeForce 940M' 'Nvidia GeForce 940MX'
 'Nvidia GeForce 960M' 'Nvidia GeForce GT 940MX' 'Nvidia GeForce GTX 1050'
 'Nvidia GeForce GTX 1050 Ti' 'Nvidia GeForce GTX 1050M'
 'Nvidia GeForce GTX 1050Ti' 'Nvidia GeForce GTX 1060'
 'Nvidia GeForce GTX 1070' 'Nvidia GeForce GTX 1070M'
 'Nvidia GeForce GTX 1080' 'Nvidia GeForce GTX 930MX'
 'Nvidia GeForce GTX 940M' 'Nvidia GeForce GTX 940MX'
 'Nvidia GeForce GTX 950M' 'Nvidia GeForce GTX 960'
 'Nvidia GeForce GTX 960<U+039C>' 'Nvidia GeForce GTX 960M'
 'Nvidia GeForce GTX 965M' 'Nvidia GeForce GTX 970M'
 'Nvidia GeForce GTX 980 ' 'Nvidia GeForce GTX 980M'
 'Nvidia GeForce GTX1050 Ti' 'Nvidia GeForce GTX1060'
 'Nvidia GeForce GTX1080' 'Nvidia GeForce MX130' 'Nvidia GeForce MX150'
 'Nvidia Quadro 3000M' 'Nvidia Quadro M1000M' 'Nvidia Quadro M1200'
 'Nvidia Quadro M2000M' 'Nvidia Quadro M2200' 'Nvidia Quadro M2200M'
 'Nvidia Quadro M3000M' 'Nvidia Quadro M500M' 'Nvidia Quadro M520M'
 'Nvidia Quadro M620' 'Nvidia Quadro M620M' 'nan']
OpSys ['Android' 'Chrome OS' 'Linux' 'Mac OS X' 'No OS' 'Windows 10'
 'Windows 10 S' 'Windows 7' 'macOS' 'nan']

In [10]:
df['Memory'].str.split('SSD').str.get(0).unique()

array(['128GB ', '128GB Flash Storage', '256GB ', '512GB ', '500GB HDD',
       '256GB Flash Storage', '1TB HDD', nan, '64GB Flash Storage',
       '32GB Flash Storage', '32GB ', '2TB HDD', '64GB ', '1.0TB Hybrid',
       '1TB ', '16GB ', '16GB Flash Storage',
       '64GB Flash Storage +  1TB HDD', '180GB ', '1TB HDD +  1TB HDD',
       '32GB HDD', '?', '512GB Flash Storage', '128GB HDD', '240GB ',
       '8GB ', '508GB Hybrid', '1.0TB HDD'], dtype=object)

In [14]:

# Sample data
data = {
    'Memory': ['256GB SSD', '1TB HDD', '512GB SSD', '2TB HDD', '128GB SSD + 1TB HDD']
}
df = pd.DataFrame(data)

# Function to parse the memory column
def parse_memory(memory):
    import re
    memory = memory.replace(' ', '').split('+')
    total_memory = 0
    memory_types = []
    
    for mem in memory:
        size, unit, type_ = re.findall(r'(\d+)([A-Za-z]+)(.*)', mem)[0]
        size = int(size)
        
        # Convert size to GB
        if unit == 'TB':
            size *= 1000
        
        total_memory += size
        memory_types.append(type_)
    
    return total_memory, ' + '.join(memory_types)

# Apply the function to the memory column
df[['Memory_Size(GB)', 'Memory_Type']] = df['Memory'].apply(lambda x: pd.Series(parse_memory(x)))

print(df)

                Memory  Memory_Size(GB) Memory_Type
0            256GB SSD              256
1              1TB HDD                1
2            512GB SSD              512
3              2TB HDD                2
4  128GB SSD + 1TB HDD              129          +

In [23]:
print(df.head())
# Extract Memory Type (SSD/HDD)
df['Memory_Type'] = df['Memory'].apply(lambda x: 'SSD' if 'SSD' in x else 'HDD')

# Extract Numeric Storage Capacity
df['Memory_Capacity_GB'] = df['Memory'].str.extract(r'(\d+)GB').astype(float)

# Display the updated DataFrame with the two new columns
print(df[['Memory_Type', 'Memory_Capacity_GB']])

                Memory  Memory_Size(GB) Memory_Type  Memory_Capacity_GB  \
0            256GB SSD              256         SSD               256.0
1              1TB HDD                1         HDD                 NaN
2            512GB SSD              512         SSD               512.0
3              2TB HDD                2         HDD                 NaN
4  128GB SSD + 1TB HDD              129         SSD               128.0

   Memory_128GB  Memory_256GB
0             0             1
1             0             0
2             0             0
3             0             0
4             1             0
  Memory_Type  Memory_Capacity_GB
0         SSD               256.0
1         HDD                 NaN
2         SSD               512.0
3         HDD                 NaN
4         SSD               128.0

In [51]:
df['Memory_Type'] = df['Memory'].apply(lambda x: 'SSD' if 'SSD' in x else 'HDD')

def extract_capacity(memory):
    if 'TB' or 'GB' in memory:
        return memory.split()[0]
    else:
        return None

df['Memory_Capacity'] = df['Memory'].apply(extract_capacity)

# Display the updated DataFrame with the two new columns
print(df[['Memory_Type', 'Memory_Capacity']])

     Memory_Type Memory_Capacity
0            SSD           128GB
1            HDD           128GB
2            SSD           256GB
3            SSD           512GB
4            SSD           256GB
...          ...             ...
1298         SSD           128GB
1299         SSD           512GB
1300         HDD            64GB
1301         HDD             1TB
1302         HDD           500GB

[1303 rows x 2 columns]

In [66]:
# Extract CPU Model and Clock Speed
df['CPUModel'] = df['Cpu'].apply(lambda x: ' '.join(x.split(' ')[0:3]))  # Extracts the CPU model
df['CPUClockSpeed'] = df['Cpu'].apply(lambda x: x.split()[-1])  # Extracts the CPU clock speed

# Drop the original 'CPU' column if needed
# df.drop(columns=['CPU'], inplace=True)

# Display the updated DataFrame with new CPU_Model and CPU_Clock_Speed columns
print(df[['Cpu', 'CPUModel', 'CPUClockSpeed']])

                                       Cpu            CPUModel CPUClockSpeed
0                     Intel Core i5 2.3GHz       Intel Core i5        2.3GHz
1                     Intel Core i5 1.8GHz       Intel Core i5        1.8GHz
2               Intel Core i5 7200U 2.5GHz       Intel Core i5        2.5GHz
3                     Intel Core i7 2.7GHz       Intel Core i7        2.7GHz
4                     Intel Core i5 3.1GHz       Intel Core i5        3.1GHz
...                                    ...                 ...           ...
1298            Intel Core i7 6500U 2.5GHz       Intel Core i7        2.5GHz
1299            Intel Core i7 6500U 2.5GHz       Intel Core i7        2.5GHz
1300  Intel Celeron Dual Core N3050 1.6GHz  Intel Celeron Dual        1.6GHz
1301            Intel Core i7 6500U 2.5GHz       Intel Core i7        2.5GHz
1302  Intel Celeron Dual Core N3050 1.6GHz  Intel Celeron Dual        1.6GHz

[1303 rows x 3 columns]

In [67]:
df['Cpu'].unique()

array(['Intel Core i5 2.3GHz', 'Intel Core i5 1.8GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core i7 2.7GHz',
       'Intel Core i5 3.1GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Core i7 2.2GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Core i5 8250U 1.6GHz', 'Intel Core i3 6006U 2GHz',
       'Intel Core i7 2.8GHz', 'Intel Core M m3 1.2GHz',
       'Intel Core i7 7500U 2.7GHz', 'Intel Core i7 2.9GHz',
       'Intel Core i3 7100U 2.4GHz', 'Intel Core i5 7300HQ 2.5GHz',
       'AMD E-Series E2-9000e 1.5GHz', 'Intel Core i5 1.6GHz',
       'Intel Core i7 8650U 1.9GHz', 'Intel Atom x5-Z8300 1.44GHz',
       'AMD E-Series E2-6110 1.5GHz', 'AMD A6-Series 9220 2.5GHz',
       'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Core i3 7130U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 2.0GHz', 'AMD Ryzen 1700 3GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Celeron Dual Core N3060 1.6GHz', 'Intel Core i5 1.3GHz',
       'AMD FX 9830P 3GHz', 'Intel Core i7 7560U 2.4GHz',
       'AMD E-Series 6110 1.5GHz', 'Intel Core i5 6200U 2.3GHz',
       'Intel Core M 6Y75 1.2GHz', 'Intel Core i5 7500U 2.7GHz',
       'Intel Core i3 6006U 2.2GHz', 'AMD A6-Series 9220 2.9GHz',
       'Intel Core i7 6920HQ 2.9GHz', 'Intel Core i5 7Y54 1.2GHz',
       'Intel Core i7 7820HK 2.9GHz', 'Intel Xeon E3-1505M V6 3GHz',
       'Intel Core i7 6500U 2.5GHz', 'AMD E-Series 9000e 1.5GHz',
       'AMD A10-Series A10-9620P 2.5GHz', 'AMD A6-Series A6-9220 2.5GHz',
       'Intel Core i5 2.9GHz', 'Intel Core i7 6600U 2.6GHz',
       'Intel Core i3 6006U 2.0GHz',
       'Intel Celeron Dual Core 3205U 1.5GHz',
       'Intel Core i7 7820HQ 2.9GHz', 'AMD A10-Series 9600P 2.4GHz',
       'Intel Core i7 7600U 2.8GHz', 'AMD A8-Series 7410 2.2GHz',
       'Intel Celeron Dual Core 3855U 1.6GHz',
       'Intel Pentium Quad Core N3710 1.6GHz',
       'AMD A12-Series 9720P 2.7GHz', 'Intel Core i5 7300U 2.6GHz',
       'AMD A12-Series 9720P 3.6GHz',
       'Intel Celeron Quad Core N3450 1.1GHz',
       'Intel Celeron Dual Core N3060 1.60GHz',
       'Intel Core i5 6440HQ 2.6GHz', 'Intel Core i7 6820HQ 2.7GHz',
       'AMD Ryzen 1600 3.2GHz', 'Intel Core i7 7Y75 1.3GHz',
       'Intel Core i5 7440HQ 2.8GHz', 'Intel Core i7 7660U 2.5GHz',
       'Intel Core i7 7700HQ 2.7GHz', 'Intel Core M m3-7Y30 2.2GHz',
       'Intel Core i5 7Y57 1.2GHz', 'Intel Core i7 6700HQ 2.6GHz',
       'Intel Core i3 6100U 2.3GHz', 'Intel Atom x5-Z8350 1.44GHz',
       'AMD A10-Series 9620P 2.5GHz', 'AMD E-Series 7110 1.8GHz',
       'Intel Celeron Dual Core N3350 2.0GHz',
       'AMD A9-Series A9-9420 3GHz', 'Intel Core i7 6820HK 2.7GHz',
       'Intel Core M 7Y30 1.0GHz', 'Intel Xeon E3-1535M v6 3.1GHz',
       'Intel Celeron Quad Core N3160 1.6GHz',
       'Intel Core i5 6300U 2.4GHz', 'Intel Core i3 6100U 2.1GHz',
       'AMD E-Series E2-9000 2.2GHz',
       'Intel Celeron Dual Core N3050 1.6GHz',
       'Intel Core M M3-6Y30 0.9GHz', 'AMD A9-Series 9420 2.9GHz',
       'Intel Core i5 6300HQ 2.3GHz', 'AMD A6-Series 7310 2GHz',
       'Intel Atom Z8350 1.92GHz', 'Intel Xeon E3-1535M v5 2.9GHz',
       'Intel Core i5 6260U 1.8GHz',
       'Intel Pentium Dual Core N4200 1.1GHz',
       'Intel Celeron Quad Core N3710 1.6GHz', 'Intel Core M 1.2GHz',
       'AMD A12-Series 9700P 2.5GHz', 'Intel Core i7 7500U 2.5GHz',
       'Intel Pentium Dual Core 4405U 2.1GHz',
       'AMD A4-Series 7210 2.2GHz', 'Intel Core i7 6560U 2.2GHz',
       'Intel Core M m7-6Y75 1.2GHz', 'AMD FX 8800P 2.1GHz',
       'Intel Core M M7-6Y75 1.2GHz', 'Intel Core i5 7200U 2.50GHz',
       'Intel Core i5 7200U 2.70GHz', 'Intel Atom X5-Z8350 1.44GHz',
       'Intel Core i5 7200U 2.7GHz', 'Intel Core M 1.1GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Pentium Dual Core 4405Y 1.5GHz',
       'Intel Pentium Quad Core N3700 1.6GHz', 'Intel Core M 6Y54 1.1GHz',
       'Intel Core i7 6500U 2.50GHz',
       'Intel Celeron Dual Core N3350 2GHz',
       'Samsung Cortex A72&A53 2.0GHz', 'AMD E-Series 9000 2.2GHz',
       'Intel Core M 6Y30 0.9GHz', 'AMD A9-Series 9410 2.9GHz'],
      dtype=object)